# sweep_config.yaml

# 1. Random Walk Sweeps
random_walk:
  # The noise scales to sweep over
  # scales: [0.05, 0.1]
  scales: [0.0005, 0.001, 0.005, 0.01] #, 0.05, 0.1]

# 2. Jump Diffusion Sweeps
jump:
  # Cartesian product of drift and probability
  drifts: [0.0, 1e-4, 1e-3]
  probs: [0.01, 0.05, 0.1]

# 3. Langevin Dynamics Sweeps
langevin:
  # Cartesian product of gradient scale (drift) and noise (rw_scale)
  drifts: [0.0, 0.01, 0.05, 0.1, 0.5]
  noises: [0.0, 1e-4, 5e-3]